[package]
name = "test-flatdata"
version = "0.1.0"
authors = ["bo <bo@nearprotocol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatdata = "0.5.1"

[build-dependencies]
flatdata = "0.5.1"
